### PR TITLE
Setup linter rules

### PR DESCRIPTION
**Pull request by ScrimpyCat**
Setup ESLint rules used by the project.

### CODE REVIEW

**Comment by ScrimpyCat** [comment]
@alexZhangKai Don't merge this as it's still in-progress (still a lot of rules I need to add), but just created the pr so if you do start on it today you can reference this if need be. Anyway there will likely be changes made to the codebase when the rules are complete, for the most part that can be handled automatically (`--fix`).

**Comment by ScrimpyCat** [comment]
@alexZhangKai Also if you do try it out and see any rules currently you really don't like, then just leave a comment here. Most of the rules added are specifically around react/react-native, so things like how components should be written, how JSX should be written, etc.

**Comment by alexZhangKai** [comment]
@ScrimpyCat Hi! I am checking out these rules. Also, I would like to have a vscode react native debugging configuration file. Do you want to add it in this commit? Or do you know a better way for debugging?

**Comment by ScrimpyCat** [comment]
@alexZhangKai Haven't used vscode on react-native projects yet so not sure what the best way to go about debugging in it is. But as far as the `.vscode/launch.json` file, you can add it in another pr. I won't add it here, since this is just regarding the ESLint config, also I probably won't add the config myself unless I start using vscode for this project. So yeh if you need one, feel free to add one.

**Pull request merged**
